name: 'codelint'
on: [push,pull_request]
jobs:
  shfmt:
    name: 'Shell format'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2

      - name: 'Test formatting'
        uses: 'bltavares/actions/shfmt@master'
        env:
          SHFMT_ARGS: '-i 2 -ci'
        with:
          path: 'ogn_install'

  shellcheck:
    name: 'Shellcheck'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v1

      - name: 'Run Shellcheck'
        uses: azohra/shell-linter@v0.3.0

      - name: 'Run Shellcheck on BATS files'
        uses: azohra/shell-linter@v0.3.0
        with:
          path: 'tests/*.bash,tests/*.bats'

  bats:
    name: 'BATS Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup BATS testing framework'
        uses: mig4/setup-bats@v1.0.1
        with:
          bats-version: 1.1.0

      - name: 'Check out code'
        uses: actions/checkout@v1

      - name: 'Get pwd location'
        run: pwd

      - name: 'Run BATS tests'
        run: sudo /opt/hostedtoolcache/BATS/1.1.0/x64/bin/bats -r tests
